### ISSUE TITLE
Yarn install fails

### ISSUE THREAD

**Issue by Ifechukwudaniel** [Kryha/scaffold-eth-2-noir#43]
### Is there an existing issue for this?

- [ ] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

➤ YN0013: │ zksync-web3@npm:0.14.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.21.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zustand@npm:4.3.8 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zwitch@npm:2.0.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ @noir-lang/acvm_js@https://git@github.com/noir-lang/acvm-js-wasm.git#commit=b9d9ca9dfc5140839f23998d9466307215607c42 can't be found in the cache
➤ YN0018: │ @noir-lang/acvm_js@https://git@github.com/noir-lang/acvm-js-wasm.git#commit=b9d9ca9dfc5140839f23998d9466307215607c42: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 28s 783ms
➤ YN0000: Failed with errors in 29s 100ms

### Expected Behavior

`yarn install`
It is supposed to install but instead it fails 

### Steps To Reproduce

All you have to do is 

`git clone git@github.com:Kryha/scaffold-eth-2-noir.git`

`yarn install`

To get my error just run the following command , I use a mac intel  

### Anything else?
acvm-js-wasm repo is now only read only  https://github.com/noir-lang/acvm-js-wasm#b9d9ca9dfc5140839f23998d9466307215607c42
_No response_

**Comment by Ifechukwudaniel** [comment]
I changed that  package
``` json 
"@noir-lang/acvm_js": "git+https://git@github.com/noir-lang/acvm-simulatorwasm.git#b9d9ca9dfc5140839f23998d9466307215607c42",
```
And it worked  perfectly, Is there any disadvantages

**Comment by Ifechukwudaniel** [comment]
@FilipHarald  what your opinion

**Comment by FilipHarald** [comment]
@Ifechukwudaniel I have now updated to nargo 0.17.0 and use NoirJS. That should do it :+1:

**Comment by Ifechukwudaniel** [comment]
Thank you
